### ISSUE TITLE
[comp: Result] add component Result

### ISSUE THREAD

**Issue by LaamGinghong** [IduxFE/components#112]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

用于反馈一系列操作任务的处理结果。

### What problem does this feature solve?
当有重要操作需告知用户处理结果，且反馈内容较为复杂时使用。

- 可以传入一个 `v-slot: extra` 来显示操作区；
- 可以传入一个 url 来自定义显示的图标，也可以传入一个 `v-slot: icon` 来显示图标；
- 可以传入 `status` 来控制按钮的颜色以及显示的图标；
- 可以传入 `title` 和 `subtitle` 来显示对应的文字，同时也支持 `slot` 的形式，优先级高于 `prop` ；
- 当需要显示复杂的说明时，可以传入一个 slot 来显示。

##### Props
| 名称 | 说明 | 类型 | 默认值 | 全局配置 | 备注 |
| --- | ------- | ----- | -------  | --------- | ------ |
| `icon` | 自定义图标 | `string \| v-slot: icon` | - | - | 传入一个 name，表示 `ix-icon` 的图标，用来替换默认的图标；也可以使用 `slot` 的形式传入，优先级高于 prop |
| `status` | 结果的状态，决定图标和颜色 | `ResultStatus` | - | ✅ | - | 
| `subtitle` | subtitle 文字 | `string \| v-slot: subtitle` | - | - | `slot` 形式优先级高于 `prop` |
| `title` | `title` 文字 | `string \| v-slot: title` | - | - | `slot` 形式优先级高于 `prop` |
```typescript
type ResultStatus = 'success' | 'error' | 'info' | 'warning' | '404' | '403' | '500'
```
##### Slots
| 名称 | 说明 | 参数类型 | 备注 |
| ----  | ----- | ---------- | ----- |
| `default` | 复杂的情况说明，用于显示更多的信息 | - | - |
| `extra` | 操作区 | - | - |

**Comment by LaamGinghong** [comment]
@danranVm 麻烦review一下 API

**Comment by huangtenghui** [comment]
title跟subtitle只支持string是否足够，需不需要支持html，有些场景可能希望高亮subtitle的某些关键字；这种情况需是否支持，还是说直接用extra去实现？

**Comment by LaamGinghong** [comment]
> title跟subtitle只支持string是否足够，需不需要支持html，solt，有些场景可能希望高亮subtitle的某些关键字或者悬浮显示详情；这种情况需是否支持，还是说直接用extra去实现？

可以增加 slot 去支持，尽量不用 html 的方式吧，避免 xss 注入

**Comment by LaamGinghong** [comment]
@huangtenghui @danranVm 已更新

**Comment by huangtenghui** [comment]
我这没啥问题了

**Comment by danranVm** [comment]
**传入一个地址覆盖默认图标，如果是动态地址请用 require 包裹**
没有太理解这句话的意思，内部实现用 `ix-icon` 的话，不是传个 name 就ok 了么？

另外 403, 404,500 之类的背景图片素材，找一下视觉吧。

**Comment by LaamGinghong** [comment]
> **传入一个地址覆盖默认图标，如果是动态地址请用 require 包裹**
> 没有太理解这句话的意思，内部实现用 `ix-icon` 的话，不是传个 name 就ok 了么？
> 
> 另外 403, 404,500 之类的背景图片素材，找一下视觉吧。

![image](https://user-images.githubusercontent.com/33472924/103846152-7752b880-50d8-11eb-8c4d-ba32cce95c3f.png)
只有是这种自定义的图标才需要传地址或者是使用 `slot`，至于你说的是用 `status` 来控制。

或者说默认是用 `status` 来控制当前的状态以及该显示的图标，如果图标你不满意，可以通过传 `icon` 来覆盖默认的图标。

**Comment by danranVm** [comment]
**地址** 是指什么？

**Comment by LaamGinghong** [comment]
> **地址** 是指什么？应该就是我说的图标的 name？叫地址有点奇怪，还有 require 包裹又是什么意思？ 能写个用法的示例么？
> 
> 我有点晕。

url 😓

**Comment by LaamGinghong** [comment]
> 还有 require 包裹又是什么意思？ 

vue的模板里面不能解析变量，所以如果传进来的是一个变量需要 require 包裹

**Comment by danranVm** [comment]
OK.  期待你的 PR
