### ISSUE TITLE
[comp: Checkbox ] add Checkbox Component

### ISSUE THREAD

**Issue by liuzaijiang** [IduxFE/components#120]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

多选框

### What does the proposed API look like?

**Checkbox**

#### Props

支持原生input属性, 例如`value, name, id`等
| 参数 | 说明 |  类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
|`checked` | 指定当前勾选框是否选中 |  `boolean`  | `false` | - | 支持双向绑定，使用时按照v-model:checked = 形式 |
|`disabled` | 禁用状态 |`boolean`| `false` | - | - |
| `indeterminate`| 是否处于不确定状态 | `boolean` | `false`| - | 当值为true时，按钮样式处于半选状态，且不受checked影响 |
| `trueValue`| 勾选框选中时返回的值 |  `string \| number`  | `true`| - | - |
| `falseValue`| 勾选框不选中时返回的值 | `string \| number` | `false`| - | - |

#### Slots

|名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
|`defalut` | 文本区域 | - | - |

#### Emits

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `change` | 点击勾选框时触发 | `Function(checkValue:boolean \| string \| number)` | - |

**Checkbox Group**
#### Group Props
| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |value
| `value` | 指定选中的选项 |  `string[]`  | `[]` | - | 支持双向绑定，使用时按照v-model:value = 形式 |
| `disabled` | 子`ix-checkbox`禁用状态 | `boolean` | `false` | - |- |
| `name` | 子`ix-checkbox` 的 name 属性 | `string` | - | - |- |

#### Group Slots
|名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
|`defalut` | `ix-checkbox`区域 | - | - |

### Group Emits
| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `change` | `value`变化时的回调函数 | `Function(checkValue:string[])` | - |

**Comment by liuzaijiang** [comment]
对于Checkbox Group的子checkbox的实现方式我们是按照ant的options属性直接传进去好还是说以插槽形式传入？
@LaamGinghong @danranVm

**Comment by LaamGinghong** [comment]
> 对于Checkbox Group的子checkbox的实现方式我们是按照ant的options属性直接传进去好还是说以插槽形式传入？
> @LaamGinghong @danranVm

我个人更倾向于使用slots的方式来实现

**Comment by LaamGinghong** [comment]
有一个疑惑，`beforeChange` 这个 API 应该是更倾向于对非受控组件的，我们的业务是否会有这样的场景？

**Comment by danranVm** [comment]
API 设计过于复杂了，checkbox 应该是一个很简单的组件才对。

几点建议：
- checbox 和 checkbox-group 的 `defaultChecked` 和 `beforeChange` 都移除。
- checkox 的 tip 移除
- checkout 的 checked 支持 v-model
- checkout-group 的 value 支持 v-model

**Comment by danranVm** [comment]
> 对于Checkbox Group的子checkbox的实现方式我们是按照ant的options属性直接传进去好还是说以插槽形式传入？
> @LaamGinghong @danranVm

暂时可以仅支持 slot ，后续可能要支持 options， slot 的优先级高于 options

**Comment by LaamGinghong** [comment]
CheckoutGroup的value应该是一个泛型，不应局限于使用string

**Comment by liuzaijiang** [comment]
> CheckoutGroup的value应该是一个泛型，不应局限于使用string

ant也只支持string，这样使用起来也简单，类型增加多了有啥好处？

**Comment by LaamGinghong** [comment]
> > CheckoutGroup的value应该是一个泛型，不应局限于使用string
> 
> ant也只支持string，这样使用起来也简单，类型增加多了有啥好处？
> @LaamGinghong

我忽略了input的value只支持string，除了去掉 `beforeChange` 以外，我没有别的问题了

**Comment by danranVm** [comment]
> > CheckoutGroup的value应该是一个泛型，不应局限于使用string
> 
> ant也只支持string，这样使用起来也简单，类型增加多了有啥好处？
> @LaamGinghong

value 的类型应该支持 any

**Comment by coolyuantao** [comment]
label呢？

**Comment by zymoplastic** [comment]
> 有一个疑惑，`beforeChange` 这个 API 应该是更倾向于对非受控组件的，我们的业务是否会有这样的场景？
> 在我看来，大部分需要使用 Checkbox 的场景应该都会使它变成受控组件，那么 `beforeChange` 这个 API 似乎意义不大。

`beforeChange` 这种比如用户点击了组件, 但是这个操作很重, 需要二次确认后生效, 如果没有这个 API, 我们只能事后再把值重新改回去, 而这种时候其实产生了副作用, 有可能某个地方 watch 了这个值得变化.

**Comment by liuzaijiang** [comment]
> label呢？

checkbox提供默认插槽来完成文本区域的功能，后续如用户需要增加tip也可以在里面自行增加
slot:
|名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
|`defalut` | checkbox文本区域 | - | - |

@coolyuantao
