### ISSUE TITLE
[comp:image ]feature image component 

### ISSUE THREAD

**Issue by lwh2015** [IduxFE/components#30]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

- 需要展示图片时使用。
- 单击图像可以放大显示 。
- 加载失败显示图像占位符。

### What does the proposed API look like?

| 属性 | 说明 | 类型  | 全局配置 |版本号|
| --- | --- | --- | --- |---|
| alt | 图像描述| string | - |-|
| fallback | 加载失败容错地址| string | - |-|
|height|图像高度|string \| number|-|-|
|preview|预览参数，为`false` 时禁用|boolean|-|-|
|src|图片地址|string|-|-|
|width|图像宽度|string \| number|-|-|
|fit|确定图片如何适应容器框，同原生 [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)|string|-|-|

**Comment by danranVm** [comment]
@zymoplastic @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by coolyuantao** [comment]
建议添加下面的支持：
1. 类似`background-size`的功能，实际图片的大小不一定跟定义的一致，这时要加适应方案
2. src是否支持`blob`（比如：`URL.createObjectURL(blob)`），或者`base64`的格式？

**Comment by lwh2015** [comment]
> 建议添加下面的支持：
> 
> 1. 类似`background-size`的功能，实际图片的大小不一定跟定义的一致，这时要加适应方案
> 2. src是否支持`blob`（比如：`URL.createObjectURL(blob)`），或者`base64`的格式？

1.会增加一个`fit`配置，适应容器框，同原生的[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
2.src支持base64的格式以及blob

**Comment by zymoplastic** [comment]
建议 `fallback`, `height`, `width` 加为全部可配置

**Comment by lwh2015** [comment]
> 建议 `fallback`, `height`, `width` 加为全局可配置

这个可以
