### ISSUE TITLE
[comp: template]: the template create by `yarn gen` report errors

### ISSUE THREAD

**Issue by LaamGinghong** [IduxFE/components#40]
### Steps to reproduce
在根目录下通过执行脚本 `yarn gen [name]` 创建对应组件。

### What is expected?
创建组件成功，组件代码无报错。

### What is actually happening?
创建组件成功，创建后的代码中包含 ts 类型错误。

### Any additional comments? (optional)

`defineComponent` 这个函数的类型不一致

**Comment by danranVm** [comment]
我这边使用 `vscode` 是正常工作的，能贴一下报错的截图吗？

感觉是不是你的编辑器没有识别到 `typings/vue-shim.d.ts`
