### ISSUE TITLE
[comp: space]: feature space component

### ISSUE THREAD

**Issue by LaamGinghong** [IduxFE/components#63]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

设置组件之间的间距，避免组件紧贴在一起，拉开统一的空间。

* 适合行内元素的水平间距
* 可以设置各种水平对齐方式

### What problem does this feature solve?
核心原理是通过 Flex 布局对组件内部的元素进行重新排布：

* 可以通过设置 `align` 设置不同的对齐方式：`start` | `center` | `end` | `baseline` ；
* 可以通过设置 `direction` 设置 **水平** 、**垂直** 两种间隔方式；
* 可以设置 `size` 设置间隔的大小，其中 size 有三种默认大小：`'small'|'middle'|'large' `，如遇到无法满足的情况，还可以传入一个 **数字** 自定义间隔大小。同时 size 允许传入一个数组，用来控制每个间隔的大小，数组的长度必须与传入的 children 长度 - 1 相等，否则会抛出警告；
* 可以以 slot 的形式传入一个 split 分隔符；
* 可以设置 `wrap` 来设置是否自动换行，仅在 `horizontal` 时有效。

#### props

| 参数 | 说明 | 类型 | 全局配置 | 默认值 | 备注 |
| ----- | ----- | ----- | ---------- | -------- | ----- |
| `align` | 对齐方式 | `start` \| `center` \| `end` \| `baseline` | - | `baseline` | - |
| `direction` | 间距方式 | `vertical` \|  `horizontal` | - | `horizontal` | - |
| `size` | 间距大小 | `Size` \| `Size[]` | `small` | - | 有三个预设间距大小，除此之外还可以传入一个数字自定义间距大小，还可以传入一个数组来控制每个间距的大小（数组长度需等于间距个数，否则组件会抛出警告） | 
| `split` | 设置拆分 | string | - | - | 设置间隔分割符，当传入 split 时，内部间距会被分隔符替代；除了这种方式，你还可以设置 `v-slot: split` 的方式设置分隔符，优先级高于 prop |
| `wrap` | 是否换行 | `boolean` | - | false | 仅在 `horizontal` 时生效 |

```typescript
type Size = 'small' | 'middle' | 'large' | number
```

#### slots
| 属性 | 说明 |
| ----- | ----- |
| `default` | 需要被间隔的内容 |
| `split` | 分隔符 |

**Comment by LaamGinghong** [comment]
@danranVm 麻烦安排一下review API

**Comment by danranVm** [comment]
@huangtenghui @danranVm 负责 review

**Comment by huangtenghui** [comment]
看了文档，然后去ant design的demo，发现跟我想象的不太一样，我想象的是居中是居于整个父容器的中间位置。

**Comment by LaamGinghong** [comment]
> 看了文档，然后去ant design的demo，发现跟我想象的不太一样，我想象的是居中是自适应整个父容器宽度，居于中间位置；看看我们是直接把这个组件做成我们想要的还是说先按ant design的搞，我们想要的后面加？目前看ant design的我们业务使用场景不多； @danranVm @coolyuantao

@huangtenghui @danranVm 找个时间讨论一下？我不知道你们的想法是咋样的

**Comment by danranVm** [comment]
@LaamGinghong 就先按照你的API 设计来吧。

不过 `align` 感觉还是用 `start、center、end` 吧，因为是有水平和垂直两种对齐方式的。

**Comment by LaamGinghong** [comment]
> @LaamGinghong 就先按照你的API 设计来吧。
> 
> 不过 `align` 感觉还是用 `start、center、end` 吧，因为是有水平和垂直两种对齐方式的。

有道理，已经修改了

**Comment by LaamGinghong** [comment]
@huangtenghui @danranVm 麻烦请重新review API

**Comment by danranVm** [comment]
- size 是否也应该支持下 全局配置 ? 类型为  'small'|'middle'|'large' ， 数组的情况不考虑。
- split 的类型 改成 `string\|Slot`，备注改成： 可以通过 `v-solt:split` 设置分隔符，插槽的优先级高于 props

**Comment by danranVm** [comment]
@LaamGinghong  其他的没什么问题了，期待你的 PR

**Comment by LaamGinghong** [comment]
@danranVm 修改了一点

**Comment by LaamGinghong** [comment]
> @danranVm 修改了一点

打算就按照这个来做了
