### ISSUE TITLE
[comp: spin] add spin component

### ISSUE THREAD

**Issue by liuzaijiang** [IduxFE/components#72]
- [ ] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

提供了加载等待的遮罩层

让用户能更好感知我们的数据请求和渲染的一个视觉效果，不会让一些动态请求加载的数据回显得很突兀，而且也能阻止用户在数据请求过程中对视图层有其他操作导致一些不必要的错误；

### What does the proposed API look like?

CONFIGS
参数 | 说明 |  类型  | 默认值 | 是否支持全局配置
-|-|-|-|-
`spinning` | 是否显示加载遮罩层|`boolean`| `true` | `false`
 `iconName`| 加载图标名称 | `string` | `loading`| `true`
 `tip`| 加载提示文字描述 |  `string`  | `false`| `true`
 `tipAlign`| 文字描述与加载图标的排列方式 | `string` | `vertical(vertical：文字排列在图标下方；horizontal： 文字排列在图标同水平方向的后方)`| `true`
 `wrapperClassName`| 组件最外包裹层class名 |  `string`  | `''`| `true`
 `size`| icon 和 tip大小控制 |  `string(small \| medium \| large)`  | `small`| `true`

SLOTS
名称 | 说明 
-|-
`defalut` | 需要遮罩的内容区域 

@danranVm @Usualminds

**Comment by danranVm** [comment]
@Usualminds @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by Usualminds** [comment]
@liuzaijiang  针对 `API` 设计，有如下建议：
- `tip` 的类型 `string | boolean` 建议直接使用 `string` ，组件内部根据是否存在该配置项来决定展示该文字描述与否
-  `tipAlign` 选项是否有 `horizontal` 场景，水平的展示效果个人感觉有点奇怪，这个看下是否需要交互把关下，另，该配置如果需要， `tipStyle` 中是否可以集成该配置？

@danranVm 看下，是否有其他建议

**Comment by liuzaijiang** [comment]
> @liuzaijiang 针对 `API` 设计，有如下建议：
> 
> * `tip` 的类型 `string | boolean` 建议直接使用 `string` ，组件内部根据是否存在该配置项来决定展示该文字描述与否
> * `tipAlign` 选项是否有 `horizontal` 场景，水平的展示效果个人感觉有点奇怪，这个看下是否需要交互把关下，另，该配置如果需要， `tipStyle` 中是否可以集成该配置？
> 
> @danranVm 看下，是否有其他建议

@Usualminds
第一点采纳
第二点中tipAlign还是需要提供`horizontal`的配置，方便交互的设计，我们默认还是`vertical`就行；另外，tipStyle和iconStyle是原生DOM的 style属性，配置说明已经加上，不能把tipAlign集成

**Comment by danranVm** [comment]
有以下几点建议：
- `iconStyle` 和 `tipStyle` 移除，新增一个 `wrapperClassName` 的API，支持全局配置。
- `iconName` => `icon` 即可
- 建议添加 `delay` 用于防止闪烁
- `tipAlign` 确实需要和视觉确认下，看有无必要。

**Comment by liuzaijiang** [comment]
> 有以下几点建议：
> 
> * `iconStyle` 和 `tipStyle` 移除，新增一个 `wrapperClassName` 的API，支持全局配置。
> * `iconName` => `icon` 即可
> * 建议添加 `delay` 用于防止闪烁
> * `tipAlign` 确实需要和视觉确认下，看有无必要。

1,2点采纳，3点目前没有发现其价值，先不实现，4点我们是提供多个选择给用户，没有影响
另外再增加size属性，控制icon和tip的大小
