### ISSUE TITLE
[cdk:utils]add unified util function to check type of the variable

### ISSUE THREAD

**Issue by clfeng** [IduxFE/components#77]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

当前项目中并没有统一的工具函数库可以用来做类型的检查，例如需要判断一个变量是否是数字，可能需要组件的开发者自行封装，这样封装检查工具函数会有大量的重复工作
### What does the proposed API look like?

使用ts进行实现相应的工具函数；使得用户可以直接使用；代码如：
```
function isNumber (val: unknown): val is number {
    return Object.prototype.toString.call(val) === '[object Number]';
}
```

**Comment by clfeng** [comment]
功能正在开发中

**Comment by danranVm** [comment]
https://github.com/IduxFE/components/blob/main/packages/components/badge/src/utils.ts

把 badge 组件中的这个 utils 移到 cdk 中，还有其他的常用工具函数一并在 cdk/utils 中提供吧。
