### ISSUE TITLE
[comp: BackTop] add BackTop component

### ISSUE THREAD

**Issue by imguolao** [IduxFE/components#79]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

- 返回页面顶部的操作按钮

### What does the proposed API look like?

Props

| 参数 | 说明 | 类型 | 默认值 | 全局配置 | 备注 |
| -- | -- | -- | --  | -- | -- |
| `target` | 需要监听其滚动事件的元素 | `string \| HTMLElement` | `window` | - | 传入 string 类型，会在 mounted 的时候使用 querySelector 来获取元素 |
| `duration` | 回到顶部所需时间（ms） | `number` | `450` |  ✅  | - |
| `visibility-height` | 滚动高度达到此参数值才出现 | `number` | `400`  |  ✅  | - |

Slots

名称 | 说明 | 参数类型 | 备注
 -- | -- | -- | --
 `defalut` | 自定义显示内容 | - | -

Emits

名称 | 说明 | 参数类型 | 备注
-- | -- | -- | --
`click` | 点击按钮触发的事件 | `event` | -

**Comment by danranVm** [comment]
@huangtenghui @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by imguolao** [comment]
@danranVm @huangtenghui 麻烦看一下 api 是否合理

**Comment by huangtenghui** [comment]
1、target 如果只支持string可能不太友好，应该也可以传dom；
2、visibility-height默认值应该是1吧，只要有滚动应该就得显示出来吧

**Comment by imguolao** [comment]
> 1、target 如果只支持string可能不太友好，应该也可以传dom；
> 2、visibility-height默认值应该是1吧，只要有滚动应该就得显示出来吧

1. 那 target 支持传入 string 和 HTMLElement
2. visibility-height 默认为 1 的话，感觉会有点奇怪，至少也得滚动到半屏后，返回顶部这个功能才起作用，否则图标过早的出现似乎没什么意义

**Comment by huangtenghui** [comment]
> > 1，target如果只支持字符串可能不太友好，应该也可以传dom；
> > 2，visibility-height设置值应该是1吧，只要有滚动应该就得显示出来吧
> 
> 1. 那目标支持字符串和HTMLElement
> 2. 能见度高度默认为1的话，感觉会有点奇怪，至少也得滚动到半屏后，返回顶部这个功能才起作用，否则图标过早的出现似乎没什么意义

ok

**Comment by danranVm** [comment]
我没什么建议。
